version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: pet-tracker-nginx
    restart: unless-stopped
    volumes:
      - ./tools/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      - pt-network
  json-server:
    build: ./tools/json-server
    ports:
      - '4000:4000'
    networks:
      - pt-network
  mf-dashboard:
    container_name: mf-dashboard-container
    image: scriptedalchemy/mf-dashboard:latest
    ports:
      - '3000:3000'
    networks:
      - pt-network
  pt-cats:
    build: ./apps/cats
    ports:
      - '1337:1337'
    networks:
      - pt-network
  pt-nav:
    build: ./remote/nav
    ports:
      - '1338:1338'
    networks:
      - pt-network
  pt-pets:
    build: ./remote/pets
    ports:
      - '1339:1339'
    networks:
      - pt-network
networks:
  pt-network:
    driver: bridge
